#-*- coding: utf-8 -*-
'''
Created on 30 авг. 2010

@author: ivan
'''
ORDER_LINEAR = "ORDER_LINEAR"
ORDER_SHUFFLE = "ORDER_SHUFFLE"
ORDER_RANDOM = "ORDER_RANDOM"

LOPPING_LOOP_ALL = "LOPPING_LOOP_ALL"
LOPPING_SINGLE = "LOPPING_SINGLE"
LOPPING_DONT_LOOP = "LOPPING_DONT_LOOP" 
 
