.TH foobnix 1 "October 20, 2006"
.SH NAME
foobnix \- GTK+ client for the Music Player Daemon
.SH SYNOPSIS
.B foobnix
[\fIOPTION\fR]
.SH DESCRIPTION
foobnix is an elegant GTK+ music client for the Music Player Daemon (MPD).
.SH OPTIONS
.TP
.B \-h\fR, \fB\-\-help
Show this help and exit
.TP
.B \-p\fR, \fB\-\-popup
Popup song notification (requires D\-Bus)
.TP
